language: node_js
sudo: false
cache:
  directories:
  - node_modules
env:
  global:
  - NODE_ENV=production
  - secure: ByYBrJTP+bQSSTXANvVkC7CLmvfgwajgvemhMjTswqmc2A+PMebOWxBAfTK+TP6F7ntJVvTo9vUMZqGafXocplSn2Qw11QeWo1xfLabDVBflZYBlOjkF/ZFe4dK53f6VNsgKrVhysTc+IufWfTqETMZGkmlf7Z8JfbERfx8G+VM8rmCioS/omELWzZn6MqWghVgkb/Wb3e6u4wUPSJF3rK8AbZ8RFD80JFqkH/zz/sTrudZUFLncokPS5H1RqTVAGCJMZbjKpmLXJQnl1TGQR9pcy1RTYELeqrk6KVedkVeYtEe987PergQJSBCvEZMEU3G0+1CNlgBxsNdFsz3ZC3E4E/1plCggi0/UffBRz2ruYGip8QiMvLlwxESrTbBrjQbmeU08h5YuTip63KSS/E8O3hdc/vYLLoX103VuiEwMBPm3CnvXVxmF8bLSeTF6Tj6ONUp7s385AIFG3TBe0Xe3f0BRXA0SeDnD4BX3RbPvM8TLbrGxpMuXQGkxxYl9IEDE5zdtM4/PBSf/9+Sml/zMxZh0PK+xLXe6OtZxARw21fy1AKm/dSEoua6Ust7iftnvovVuk2iUERb6YTsgBl+A+pYLEZ7Nc5WAV6uFWRncH4AlDJwghTh9Ibm1tofKfoADpbJD4QwXDhqms+PVOn9BtlrjhDVYoeZCKwKic4k=
  - secure: ddrRk46EWzEIUFuaIXUmImkEQXw3zHSp+Vx3ZuomUK/j+PoeO20EN/82qjmf71kEKMfktP/iwTqfrlgIjg0fWDHrCwidt6XmEAq1z2mPLSxZnxhd48oXxyUkS+TOzlFjxR57mGxt+EZEEYd5bnAnFW4b2pVdf+ohVt2HNUMlpCd6B4toLzazllAHOmdVzUN5+FozW83nhDYby4KooHVXt0OriQPu2NiREBwqCv8TNLQQQ8Eex5Z1CjPppfjEGtPy3msWQQmN21UFhKXz18DKpovAsfWWIz+Uv0/XZeFvk2g4mxbA3KsxtOP0mLli7avM3NuBAUujrEfaoQnXG4qnDrAWzlximKWP7+m7mF0HCKLzNQ8S85ca7t41ZpElXO/Wf0yqkbOveE11TULpTw38UtuCVDcL/TDm/vosBSsm8h5QJnrGEpyh0k94+UDFTy8sme7+k99VLnPxm+kzmFNcSwfoADrE2HKvAxTVrR6KzgxsUFTdwhbm6d34r+UEVcTsMOu20Q1O9ttMA9vNiZ2OqG1vSTNG5+j6T3yJv/NMgofcQiZWct+MiJMJWiO4ldtiLhADe7Nsk6ImvMJsK9hkcCB71foxkKEie3X6VJNcJi3AylyzDLM2EqXUc0WJn8/Brt1Gb33OE/RCq71pVwzPsXjL9Eyof0XPD+ze8r3AX54=
script:
- npm run lint
before_deploy:
- npm run build
- cp index-prod.html dist/index.html
deploy:
  provider: s3
  region: us-east-1
  bucket: bosfoodfails.bjacobel.com
  acl: public_read
  local_dir: dist
  skip_cleanup: true
  on:
    branch: master
after_deploy:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id E3JWF4CX0SVUF5 --paths /index.html /main.js /main.css
